"""Add many-to-many relationships for product attributes

Revision ID: 733c1a343e38
Revises: c72948e7361c
Create Date: 2025-07-13 17:39:02.165595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '733c1a343e38'
down_revision: Union[str, Sequence[str], None] = 'c72948e7361c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_body_types',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('body_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'body_type')
    )
    op.create_table('product_color_types',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('color_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'color_type')
    )
    op.create_table('product_heights',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('height', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'height')
    )
    op.create_table('product_kibbe_types',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('kibbe_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'kibbe_type')
    )
    op.drop_column('product_attributes', 'kibbe_type')
    op.drop_column('product_attributes', 'color_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_attributes', sa.Column('color_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('product_attributes', sa.Column('kibbe_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('product_kibbe_types')
    op.drop_table('product_heights')
    op.drop_table('product_color_types')
    op.drop_table('product_body_types')
    # ### end Alembic commands ###
